Fix git access token not being sent in header
comp500/packwiz-installer-bootstrap pull request #8
Opened 2023-03-05 21:32 UTC by fuzzyweapon

I found a bug in latest (v0.0.3).  Github API began complaining about needing the tokens to be passed in the request header, which of course, stops packwiz dead in its tracks if you've passed a token in.

Typically, these authorization header tokens are done with "Authorization" as the key name, which worked when I tested it.

In addition, I did some minor cleanup for readability and maintainability.

Last, but not least, I setup the `application` Gradle plugin to run results in a new build subfolder `<gradle_build_dir>/test-project` where the default is `<project_dir>/build/test-project`.

2023-03-05 21:42 UTC, fuzzyweapon commented
Looks like this was packwiz/packwiz-installer#49

Just found it after doing all of this lol.  It was a good little exercise though so oh well!  Shouldn't hurt to accept it before you move to your maven repo.

2023-03-06 19:31 UTC, comp500 commented
Thanks for the PR! I'll definitely merge this - I ought to have merged [the previous PR that also did this](https://github.com/packwiz/packwiz-installer-bootstrap/pull/5) but I thought the rewrite would take less time than it has :P

I definitely should push my progress somewhere, hopefully I can get the rewrite finished fairly soon.

2023-03-06 19:33 UTC, comp500 requested changes

2023-03-06 19:33 UTC, comp500 commented on src/main/java/link/infra/packwiz/installer/bootstrap/Bootstrap.java
> +			throw new GithubException("$displayName (" + property + ") cannot be found");
Java doesn't have string templating :P

```suggestion
			throw new GithubException(displayName + " (" + property + ") cannot be found");
```

2023-03-07 19:09 UTC, fuzzyweapon commented
Yeah.  I'd love to see it.  I'm getting more invested on working on it more
as I've been looking through the code more and more, but I'm a little
hesitant because it sounds like you've got big stuff in the works.

On Mon, Mar 6, 2023 at 11:31 AM comp500 ***@***.***> wrote:

> Thanks for the PR! I'll definitely merge this - I ought to have merged the
> previous PR that also did this
> <https://github.com/packwiz/packwiz-installer-bootstrap/pull/5> but I
> thought the rewrite would take less time than it has :P
>
> I definitely should push my progress somewhere, hopefully I can get the
> rewrite finished fairly soon.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/packwiz/packwiz-installer-bootstrap/pull/8#issuecomment-1456831267>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAJSAF4F2CL5CPSMQV5GLSDW2Y3RLANCNFSM6AAAAAAVQMWKZA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-03-17 20:58 UTC, merged

2024-08-03 11:36 UTC, xtexChooser commented
is there any releases or prebuilt binary with this patch available?